version: '3'

services:

  web:
    image: nginx
    ports:
      - "1111:1111"
    volumes:
      - ./application/codeigniter:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
        - backend

  php:
    image: php-ls
    volumes:
      - ./application/codeigniter:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 9000:9000
    depends_on:
      - db
    networks:
        - backend

  db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
        - backend

networks:
    backend: